### ISSUE TITLE
there are no instructions for installing deps. I get this error:

### ISSUE THREAD

**Issue by foxjazz** [schmee/zig-raylib-imgui-template#1]
running on a mac I get:
zig build
/Volumes/Littleboy/Code/zig-raylib-imgui-template/build.zig.zon:15:18: error: dependency is missing 'url' field
        .zgui = .{ .path = "vendor/zgui" },

**Comment by schmee** [comment]
Hi @foxjazz, thanks for the report.

I have not updated this repo for Zig 0.12 yet since it just came out, so it might be broken at the moment. I hope to get around to it soon! 🙏

**Comment by foxjazz** [comment]
I was using 11, I just brewed into 12 a few minutes ago.  Thanks for the info.

**Comment by schmee** [comment]
@foxjazz I've just pushed an update that's compatible with Zig 0.12, does it work for you if you follow the steps in the README? https://github.com/schmee/zig-raylib-imgui-template?tab=readme-ov-file#build

**Comment by schmee** [comment]
I believe that this is solved, feel free to re-open the issue if that's not the case 👍
